# Generated by Django 3.2.10 on 2022-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
                ('email', models.CharField(default='', max_length=500, null=True)),
                ('managearea', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carnumber', models.CharField(default='', max_length=500, null=True)),
                ('type', models.CharField(default='', max_length=500, null=True)),
                ('firm', models.CharField(default='', max_length=500, null=True)),
                ('model', models.CharField(default='', max_length=500, null=True)),
                ('caryear', models.CharField(default='', max_length=500, null=True)),
                ('color', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordereval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rescueorder', models.CharField(default='', max_length=500, null=True)),
                ('rescueorderid', models.CharField(default='', max_length=500, null=True)),
                ('content', models.CharField(default='', max_length=500, null=True)),
                ('addtime', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repairman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
                ('email', models.CharField(default='', max_length=500, null=True)),
                ('address', models.CharField(default='', max_length=500, null=True)),
                ('allowtype', models.CharField(default='', max_length=500, null=True)),
                ('state', models.CharField(default='', max_length=500, null=True)),
                ('bankcard', models.CharField(default='', max_length=500, null=True)),
                ('payslip', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rescueorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(default='', max_length=500, null=True)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('car', models.CharField(default='', max_length=500, null=True)),
                ('carid', models.CharField(default='', max_length=500, null=True)),
                ('troubletype', models.CharField(default='', max_length=500, null=True)),
                ('rescaddress', models.CharField(default='', max_length=500, null=True)),
                ('troubledesc', models.CharField(default='', max_length=500, null=True)),
                ('reason', models.CharField(default='', max_length=500, null=True)),
                ('orderstate', models.CharField(default='', max_length=500, null=True)),
                ('precost', models.CharField(default='', max_length=500, null=True)),
                ('predate', models.CharField(default='', max_length=500, null=True)),
                ('duration', models.CharField(default='', max_length=500, null=True)),
                ('repairman', models.CharField(default='', max_length=500, null=True)),
                ('repairmanid', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repairman', models.CharField(default='', max_length=500, null=True)),
                ('repairmanid', models.CharField(default='', max_length=500, null=True)),
                ('content', models.CharField(default='', max_length=500, null=True)),
                ('plandate', models.CharField(default='', max_length=500, null=True)),
                ('state', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=500, null=True)),
                ('userid', models.CharField(default='', max_length=500, null=True)),
                ('price', models.CharField(default='', max_length=500, null=True)),
                ('substate', models.CharField(default='', max_length=500, null=True)),
                ('chargetype', models.CharField(default='', max_length=500, null=True)),
                ('paytype', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500, null=True)),
                ('username', models.CharField(default='', max_length=500, null=True)),
                ('password', models.CharField(default='', max_length=500, null=True)),
                ('birthday', models.CharField(default='', max_length=500, null=True)),
                ('sex', models.CharField(default='', max_length=500, null=True)),
                ('email', models.CharField(default='', max_length=500, null=True)),
                ('homeaddress', models.CharField(default='', max_length=500, null=True)),
                ('emercontact', models.CharField(default='', max_length=500, null=True)),
                ('bankcard', models.CharField(default='', max_length=500, null=True)),
                ('payslip', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
